<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Domain\ERP.Domain.csproj" />
    <ProjectReference Include="..\ERP.Infraestructure\ERP.Infraestructure.csproj" />
    <ProjectReference Include="..\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
