// <auto-generated />
using System;
using ERP.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009022109_AddMoreWarehouses")]
    partial class AddMoreWarehouses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCategory")
                        .HasName("PK_CategoriaRopa");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_CategoriaRopa_DescripcionCategoria");

                    b.ToTable("Category", "dbo");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            CategoryName = "Ropa"
                        },
                        new
                        {
                            IdCategory = 2,
                            CategoryName = "Zapatos"
                        },
                        new
                        {
                            IdCategory = 3,
                            CategoryName = "Bolsos"
                        },
                        new
                        {
                            IdCategory = 4,
                            CategoryName = "Accesorios"
                        },
                        new
                        {
                            IdCategory = 5,
                            CategoryName = "Ropa Deportiva"
                        },
                        new
                        {
                            IdCategory = 6,
                            CategoryName = "Ropa Interior"
                        },
                        new
                        {
                            IdCategory = 7,
                            CategoryName = "Joyería"
                        },
                        new
                        {
                            IdCategory = 8,
                            CategoryName = "Cinturones"
                        },
                        new
                        {
                            IdCategory = 9,
                            CategoryName = "Gorras y Sombreros"
                        },
                        new
                        {
                            IdCategory = 10,
                            CategoryName = "Otros"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.CreditCard", b =>
                {
                    b.Property<int>("IdCreditCard")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCreditCard")
                        .HasName("PK_Tarjeta");

                    b.HasIndex(new[] { "CreditCardName" }, "UQ_Tarjeta_DescripcionTarjeta")
                        .IsUnique();

                    b.ToTable("CreditCard");

                    b.HasData(
                        new
                        {
                            IdCreditCard = 1,
                            CreditCardName = "Visa"
                        },
                        new
                        {
                            IdCreditCard = 2,
                            CreditCardName = "Mastercard"
                        },
                        new
                        {
                            IdCreditCard = 3,
                            CreditCardName = "American Express"
                        },
                        new
                        {
                            IdCreditCard = 4,
                            CreditCardName = "Discover"
                        },
                        new
                        {
                            IdCreditCard = 5,
                            CreditCardName = "Diners Club"
                        },
                        new
                        {
                            IdCreditCard = 6,
                            CreditCardName = "JCB"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("IdCustomer")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("IdProvince")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdCustomer")
                        .HasName("PK_Cliente");

                    b.HasIndex("IdProvince");

                    b.HasIndex(new[] { "Email" }, "UQ_Cliente_Email")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdCreditCard")
                        .HasColumnType("int");

                    b.Property<string>("IdCustomer")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<int>("IdInvoiceStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdPaymentType")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("IdInvoice")
                        .HasName("PK_FacturaEncabezado");

                    b.HasIndex("IdCreditCard");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdInvoiceStatus");

                    b.HasIndex("IdPaymentType");

                    b.HasIndex("IdUser");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdTax")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdInvoice", "LineNumber")
                        .HasName("PK_InvoiceItems");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdTax");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Property<int>("IdInvoiceStatus")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceStatusDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdInvoiceStatus")
                        .HasName("PK_EstadoFactura");

                    b.HasIndex(new[] { "InvoiceStatusDescription" }, "UQ_EstadoFactura_DescripcionEstado")
                        .IsUnique();

                    b.ToTable("InvoiceStatuse");

                    b.HasData(
                        new
                        {
                            IdInvoiceStatus = 1,
                            InvoiceStatusDescription = "Pendiente"
                        },
                        new
                        {
                            IdInvoiceStatus = 2,
                            InvoiceStatusDescription = "Pagada"
                        },
                        new
                        {
                            IdInvoiceStatus = 3,
                            InvoiceStatusDescription = "Anulada"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PaymentType", b =>
                {
                    b.Property<int>("IdPaymentType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypeDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdPaymentType")
                        .HasName("PK_TipoPago");

                    b.HasIndex(new[] { "PaymentTypeDescription" }, "UQ_TipoPago_DescripcionTipoPago")
                        .IsUnique();

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            IdPaymentType = 1,
                            PaymentTypeDescription = "Efectivo"
                        },
                        new
                        {
                            IdPaymentType = 2,
                            PaymentTypeDescription = "Tarjeta de Crédito"
                        },
                        new
                        {
                            IdPaymentType = 3,
                            PaymentTypeDescription = "Tarjeta de Débito"
                        },
                        new
                        {
                            IdPaymentType = 4,
                            PaymentTypeDescription = "Transferencia Bancaria"
                        },
                        new
                        {
                            IdPaymentType = 5,
                            PaymentTypeDescription = "SINPE Móvil"
                        },
                        new
                        {
                            IdPaymentType = 6,
                            PaymentTypeDescription = "PayPal"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("IdProduct")
                        .HasName("PK_Ropa");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ProductSupplier", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.HasKey("IdProduct", "IdSupplier")
                        .HasName("PK_RopaProveedor");

                    b.HasIndex("IdSupplier");

                    b.ToTable("ProductSupplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Province", b =>
                {
                    b.Property<int>("IdProvince")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProvince")
                        .HasName("PK_Provincia");

                    b.HasIndex(new[] { "ProvinceName" }, "UQ_Provincia_Descripcion")
                        .IsUnique();

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            IdProvince = 1,
                            ProvinceName = "San José"
                        },
                        new
                        {
                            IdProvince = 2,
                            ProvinceName = "Alajuela"
                        },
                        new
                        {
                            IdProvince = 3,
                            ProvinceName = "Cartago"
                        },
                        new
                        {
                            IdProvince = 4,
                            ProvinceName = "Heredia"
                        },
                        new
                        {
                            IdProvince = 5,
                            ProvinceName = "Guanacaste"
                        },
                        new
                        {
                            IdProvince = 6,
                            ProvinceName = "Puntarenas"
                        },
                        new
                        {
                            IdProvince = 7,
                            ProvinceName = "Limón"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRole")
                        .HasName("PK_Rol");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Rol_DescripcionRol")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            IdRole = 2,
                            RoleName = "Vendedor"
                        },
                        new
                        {
                            IdRole = 3,
                            RoleName = "Cliente"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LegalEntityNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSupplier")
                        .HasName("PK_Proveedor");

                    b.HasIndex(new[] { "LegalEntityNumber" }, "UQ_Proveedor_CedulaJuridica")
                        .IsUnique()
                        .HasFilter("[LegalEntityNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ_Proveedor_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Tax", b =>
                {
                    b.Property<int>("IdTax")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTax")
                        .HasName("PK_Impuesto");

                    b.HasIndex(new[] { "TaxName" }, "UQ_Impuesto_DescripcionImpuesto")
                        .IsUnique();

                    b.ToTable("Taxe");

                    b.HasData(
                        new
                        {
                            IdTax = 1,
                            Percentage = 13m,
                            TaxName = "Impuesto de Ventas"
                        },
                        new
                        {
                            IdTax = 2,
                            Percentage = 15m,
                            TaxName = "Impuesto Selectivo"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdUser")
                        .HasName("PK_Usuario");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuario_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "UQ_Usuario_Login")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdWarehouse")
                        .HasName("PK_Bodega");

                    b.HasIndex(new[] { "WarehouseName" }, "UQ_Bodega_DescripcionBodega")
                        .IsUnique();

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            IdWarehouse = 1,
                            Address = "San José Centro",
                            WarehouseName = "Bodega Central"
                        },
                        new
                        {
                            IdWarehouse = 2,
                            Address = "Escazú, San José",
                            WarehouseName = "Sucursal Escazú"
                        },
                        new
                        {
                            IdWarehouse = 3,
                            Address = "Heredia Centro",
                            WarehouseName = "Sucursal Heredia"
                        },
                        new
                        {
                            IdWarehouse = 4,
                            Address = "Alajuela Centro",
                            WarehouseName = "Sucursal Alajuela"
                        },
                        new
                        {
                            IdWarehouse = 5,
                            Address = "Cartago Centro",
                            WarehouseName = "Sucursal Cartago"
                        },
                        new
                        {
                            IdWarehouse = 6,
                            Address = "San Carlos, Alajuela",
                            WarehouseName = "Centro de Distribución Norte"
                        },
                        new
                        {
                            IdWarehouse = 7,
                            Address = "Pérez Zeledón, San José",
                            WarehouseName = "Centro de Distribución Sur"
                        },
                        new
                        {
                            IdWarehouse = 11,
                            Address = "San José, San José",
                            WarehouseName = "Bodega Central San José"
                        },
                        new
                        {
                            IdWarehouse = 12,
                            Address = "San José, Escazú",
                            WarehouseName = "Bodega Metropolitana Escazú"
                        },
                        new
                        {
                            IdWarehouse = 13,
                            Address = "San José, Desamparados",
                            WarehouseName = "Bodega Logística Desamparados"
                        },
                        new
                        {
                            IdWarehouse = 14,
                            Address = "Alajuela, Alajuela",
                            WarehouseName = "Bodega Regional Alajuela"
                        },
                        new
                        {
                            IdWarehouse = 15,
                            Address = "Alajuela, San Ramón",
                            WarehouseName = "Bodega Occidente San Ramón"
                        },
                        new
                        {
                            IdWarehouse = 16,
                            Address = "Cartago, Cartago",
                            WarehouseName = "Bodega Industrial Cartago"
                        },
                        new
                        {
                            IdWarehouse = 17,
                            Address = "Cartago, Paraíso",
                            WarehouseName = "Bodega Valle de Paraíso"
                        },
                        new
                        {
                            IdWarehouse = 18,
                            Address = "Heredia, Heredia",
                            WarehouseName = "Bodega Heredia Norte"
                        },
                        new
                        {
                            IdWarehouse = 19,
                            Address = "Guanacaste, Liberia",
                            WarehouseName = "Bodega Guanacaste Liberia"
                        },
                        new
                        {
                            IdWarehouse = 20,
                            Address = "Puntarenas, Puntarenas",
                            WarehouseName = "Bodega Pacífico Puntarenas"
                        },
                        new
                        {
                            IdWarehouse = 21,
                            Address = "San José, Tibás",
                            WarehouseName = "Bodega Central Tibás"
                        },
                        new
                        {
                            IdWarehouse = 22,
                            Address = "San José, Moravia",
                            WarehouseName = "Bodega Logística Moravia"
                        },
                        new
                        {
                            IdWarehouse = 23,
                            Address = "San José, Goicoechea",
                            WarehouseName = "Bodega Metropolitana Goicoechea"
                        },
                        new
                        {
                            IdWarehouse = 24,
                            Address = "San José, Curridabat",
                            WarehouseName = "Bodega Este Curridabat"
                        },
                        new
                        {
                            IdWarehouse = 25,
                            Address = "San José, Aserrí",
                            WarehouseName = "Bodega Sur Aserrí"
                        },
                        new
                        {
                            IdWarehouse = 26,
                            Address = "San José, Puriscal",
                            WarehouseName = "Bodega Valle Puriscal"
                        },
                        new
                        {
                            IdWarehouse = 27,
                            Address = "San José, Turrubares",
                            WarehouseName = "Bodega Industrial Turrubares"
                        },
                        new
                        {
                            IdWarehouse = 28,
                            Address = "San José, Dota",
                            WarehouseName = "Bodega Regional Dota"
                        },
                        new
                        {
                            IdWarehouse = 29,
                            Address = "San José, Tarrazú",
                            WarehouseName = "Bodega Montaña Tarrazú"
                        },
                        new
                        {
                            IdWarehouse = 30,
                            Address = "San José, León Cortés",
                            WarehouseName = "Bodega Los Santos León Cortés"
                        },
                        new
                        {
                            IdWarehouse = 31,
                            Address = "Alajuela, Grecia",
                            WarehouseName = "Bodega Norte Grecia"
                        },
                        new
                        {
                            IdWarehouse = 32,
                            Address = "Alajuela, Naranjo",
                            WarehouseName = "Bodega Occidente Naranjo"
                        },
                        new
                        {
                            IdWarehouse = 33,
                            Address = "Alajuela, Palmares",
                            WarehouseName = "Bodega Cafetal Palmares"
                        },
                        new
                        {
                            IdWarehouse = 34,
                            Address = "Alajuela, Poás",
                            WarehouseName = "Bodega Industrial Poás"
                        },
                        new
                        {
                            IdWarehouse = 35,
                            Address = "Alajuela, Atenas",
                            WarehouseName = "Bodega Volcán Atenas"
                        },
                        new
                        {
                            IdWarehouse = 36,
                            Address = "Alajuela, Orotina",
                            WarehouseName = "Bodega Regional Orotina"
                        },
                        new
                        {
                            IdWarehouse = 37,
                            Address = "Alajuela, San Carlos",
                            WarehouseName = "Bodega Frontera San Carlos"
                        },
                        new
                        {
                            IdWarehouse = 38,
                            Address = "Alajuela, Guatuso",
                            WarehouseName = "Bodega Pital Guatuso"
                        },
                        new
                        {
                            IdWarehouse = 39,
                            Address = "Alajuela, Upala",
                            WarehouseName = "Bodega Norte Upala"
                        },
                        new
                        {
                            IdWarehouse = 40,
                            Address = "Alajuela, Los Chiles",
                            WarehouseName = "Bodega Llanuras Los Chiles"
                        },
                        new
                        {
                            IdWarehouse = 41,
                            Address = "Cartago, Cartago",
                            WarehouseName = "Bodega Cartago Centro"
                        },
                        new
                        {
                            IdWarehouse = 42,
                            Address = "Cartago, Oreamuno",
                            WarehouseName = "Bodega Valle Oreamuno"
                        },
                        new
                        {
                            IdWarehouse = 43,
                            Address = "Cartago, El Guarco",
                            WarehouseName = "Bodega Colonial El Guarco"
                        },
                        new
                        {
                            IdWarehouse = 44,
                            Address = "Cartago, Alvarado",
                            WarehouseName = "Bodega Norte Alvarado"
                        },
                        new
                        {
                            IdWarehouse = 45,
                            Address = "Cartago, Jiménez",
                            WarehouseName = "Bodega Este Jiménez"
                        },
                        new
                        {
                            IdWarehouse = 46,
                            Address = "Cartago, Turrialba",
                            WarehouseName = "Bodega Agrícola Turrialba"
                        },
                        new
                        {
                            IdWarehouse = 47,
                            Address = "Cartago, Paraíso",
                            WarehouseName = "Bodega Valle Central Paraíso"
                        },
                        new
                        {
                            IdWarehouse = 48,
                            Address = "Cartago, Alvarado",
                            WarehouseName = "Bodega Montaña Cervantes"
                        },
                        new
                        {
                            IdWarehouse = 49,
                            Address = "Cartago, Jiménez",
                            WarehouseName = "Bodega Industrial Tucurrique"
                        },
                        new
                        {
                            IdWarehouse = 50,
                            Address = "Cartago, Jiménez",
                            WarehouseName = "Bodega Logística Juan Viñas"
                        },
                        new
                        {
                            IdWarehouse = 51,
                            Address = "Heredia, Heredia",
                            WarehouseName = "Bodega Heredia Central"
                        },
                        new
                        {
                            IdWarehouse = 52,
                            Address = "Heredia, Barva",
                            WarehouseName = "Bodega Metropolitana Barva"
                        },
                        new
                        {
                            IdWarehouse = 53,
                            Address = "Heredia, Santo Domingo",
                            WarehouseName = "Bodega Regional Santo Domingo"
                        },
                        new
                        {
                            IdWarehouse = 54,
                            Address = "Heredia, Santa Bárbara",
                            WarehouseName = "Bodega Industrial Santa Bárbara"
                        },
                        new
                        {
                            IdWarehouse = 55,
                            Address = "Heredia, San Rafael",
                            WarehouseName = "Bodega Norte San Rafael"
                        },
                        new
                        {
                            IdWarehouse = 56,
                            Address = "Heredia, San Isidro",
                            WarehouseName = "Bodega Bosque San Isidro"
                        },
                        new
                        {
                            IdWarehouse = 57,
                            Address = "Heredia, Flores",
                            WarehouseName = "Bodega Flores Centro"
                        },
                        new
                        {
                            IdWarehouse = 58,
                            Address = "Heredia, Belén",
                            WarehouseName = "Bodega Café Belén"
                        },
                        new
                        {
                            IdWarehouse = 59,
                            Address = "Heredia, Sarapiquí",
                            WarehouseName = "Bodega Aurora Sarapiquí"
                        },
                        new
                        {
                            IdWarehouse = 60,
                            Address = "Heredia, Sarapiquí",
                            WarehouseName = "Bodega Logística Horquetas"
                        },
                        new
                        {
                            IdWarehouse = 61,
                            Address = "Guanacaste, Liberia",
                            WarehouseName = "Bodega Guanacaste Liberia Norte"
                        },
                        new
                        {
                            IdWarehouse = 62,
                            Address = "Guanacaste, Nicoya",
                            WarehouseName = "Bodega Pampa Nicoya"
                        },
                        new
                        {
                            IdWarehouse = 63,
                            Address = "Guanacaste, Santa Cruz",
                            WarehouseName = "Bodega Chorotega Santa Cruz"
                        },
                        new
                        {
                            IdWarehouse = 64,
                            Address = "Guanacaste, Carrillo",
                            WarehouseName = "Bodega Costera Carrillo"
                        },
                        new
                        {
                            IdWarehouse = 65,
                            Address = "Guanacaste, La Cruz",
                            WarehouseName = "Bodega Frontera La Cruz"
                        },
                        new
                        {
                            IdWarehouse = 66,
                            Address = "Guanacaste, Bagaces",
                            WarehouseName = "Bodega Industrial Bagaces"
                        },
                        new
                        {
                            IdWarehouse = 67,
                            Address = "Guanacaste, Cañas",
                            WarehouseName = "Bodega Río Cañas"
                        },
                        new
                        {
                            IdWarehouse = 68,
                            Address = "Guanacaste, Abangares",
                            WarehouseName = "Bodega Logística Abangares"
                        },
                        new
                        {
                            IdWarehouse = 69,
                            Address = "Guanacaste, Tilarán",
                            WarehouseName = "Bodega Norte Tilarán"
                        },
                        new
                        {
                            IdWarehouse = 70,
                            Address = "Guanacaste, Upala",
                            WarehouseName = "Bodega Volcán Upala"
                        },
                        new
                        {
                            IdWarehouse = 71,
                            Address = "Puntarenas, Puntarenas",
                            WarehouseName = "Bodega Pacífico Puntarenas Centro"
                        },
                        new
                        {
                            IdWarehouse = 72,
                            Address = "Puntarenas, Esparza",
                            WarehouseName = "Bodega Puerto Esparza"
                        },
                        new
                        {
                            IdWarehouse = 73,
                            Address = "Puntarenas, Montes de Oro",
                            WarehouseName = "Bodega Costanera Montes de Oro"
                        },
                        new
                        {
                            IdWarehouse = 74,
                            Address = "Puntarenas, Osa",
                            WarehouseName = "Bodega Sur Osa"
                        },
                        new
                        {
                            IdWarehouse = 75,
                            Address = "Puntarenas, Golfito",
                            WarehouseName = "Bodega Península Golfito"
                        },
                        new
                        {
                            IdWarehouse = 76,
                            Address = "Puntarenas, Coto Brus",
                            WarehouseName = "Bodega Regional Coto Brus"
                        },
                        new
                        {
                            IdWarehouse = 77,
                            Address = "Puntarenas, Quepos",
                            WarehouseName = "Bodega Pacífico Central Quepos"
                        },
                        new
                        {
                            IdWarehouse = 78,
                            Address = "Puntarenas, Parrita",
                            WarehouseName = "Bodega Isla Parrita"
                        },
                        new
                        {
                            IdWarehouse = 79,
                            Address = "Puntarenas, Corredores",
                            WarehouseName = "Bodega Peninsular Corredores"
                        },
                        new
                        {
                            IdWarehouse = 80,
                            Address = "Puntarenas, Garabito",
                            WarehouseName = "Bodega Costera Garabito"
                        },
                        new
                        {
                            IdWarehouse = 81,
                            Address = "Limón, Limón",
                            WarehouseName = "Bodega Caribe Limón"
                        },
                        new
                        {
                            IdWarehouse = 82,
                            Address = "Limón, Pococí",
                            WarehouseName = "Bodega Atlántica Pococí"
                        },
                        new
                        {
                            IdWarehouse = 83,
                            Address = "Limón, Siquirres",
                            WarehouseName = "Bodega Bananera Siquirres"
                        },
                        new
                        {
                            IdWarehouse = 84,
                            Address = "Limón, Matina",
                            WarehouseName = "Bodega Costera Matina"
                        },
                        new
                        {
                            IdWarehouse = 85,
                            Address = "Limón, Talamanca",
                            WarehouseName = "Bodega Caribe Sur Talamanca"
                        },
                        new
                        {
                            IdWarehouse = 86,
                            Address = "Limón, Guácimo",
                            WarehouseName = "Bodega Portuaria Guácimo"
                        },
                        new
                        {
                            IdWarehouse = 87,
                            Address = "Limón, Pococí",
                            WarehouseName = "Bodega Logística Cariari"
                        },
                        new
                        {
                            IdWarehouse = 88,
                            Address = "Limón, Talamanca",
                            WarehouseName = "Bodega Regional Bratsi"
                        },
                        new
                        {
                            IdWarehouse = 89,
                            Address = "Limón, Matina",
                            WarehouseName = "Bodega Industrial Batán"
                        },
                        new
                        {
                            IdWarehouse = 90,
                            Address = "Limón, Limón",
                            WarehouseName = "Bodega Atlántico Centro"
                        },
                        new
                        {
                            IdWarehouse = 91,
                            Address = "San José, Montes de Oca",
                            WarehouseName = "Bodega Valle Central Montes de Oca"
                        },
                        new
                        {
                            IdWarehouse = 92,
                            Address = "San José, Vásquez de Coronado",
                            WarehouseName = "Bodega Empresarial Vásquez de Coronado"
                        },
                        new
                        {
                            IdWarehouse = 93,
                            Address = "San José, Acosta",
                            WarehouseName = "Bodega Comercial Acosta"
                        },
                        new
                        {
                            IdWarehouse = 94,
                            Address = "San José, Mora",
                            WarehouseName = "Bodega Desarrollo Mora"
                        },
                        new
                        {
                            IdWarehouse = 95,
                            Address = "San José, Santa Ana",
                            WarehouseName = "Bodega Logística Santa Ana"
                        },
                        new
                        {
                            IdWarehouse = 96,
                            Address = "San José, Alajuelita",
                            WarehouseName = "Bodega Industrial Alajuelita"
                        },
                        new
                        {
                            IdWarehouse = 97,
                            Address = "San José, Pérez Zeledón",
                            WarehouseName = "Bodega Centro Pérez Zeledón"
                        },
                        new
                        {
                            IdWarehouse = 98,
                            Address = "Puntarenas, Buenos Aires",
                            WarehouseName = "Bodega Regional Buenos Aires"
                        },
                        new
                        {
                            IdWarehouse = 99,
                            Address = "Alajuela, San Mateo",
                            WarehouseName = "Bodega Estratégica San Mateo"
                        },
                        new
                        {
                            IdWarehouse = 100,
                            Address = "Alajuela, Río Cuarto",
                            WarehouseName = "Bodega Distribución Río Cuarto"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Province", "Province")
                        .WithMany("Customers")
                        .HasForeignKey("IdProvince")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Provincia");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("ERP.Domain.Entities.CreditCard", "CreditCard")
                        .WithMany("Invoices")
                        .HasForeignKey("IdCreditCard")
                        .HasConstraintName("FK_FacturaEncabezado_Tarjeta");

                    b.HasOne("ERP.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("IdCustomer")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_Cliente");

                    b.HasOne("ERP.Domain.Entities.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("IdInvoiceStatus")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_EstadoFactura");

                    b.HasOne("ERP.Domain.Entities.PaymentType", "PaymentType")
                        .WithMany("Invoices")
                        .HasForeignKey("IdPaymentType")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_TipoPago");

                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_Usuario");

                    b.Navigation("CreditCard");

                    b.Navigation("Customer");

                    b.Navigation("InvoiceStatus");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdInvoice")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_Invoice");

                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaDetalle_Ropa");

                    b.HasOne("ERP.Domain.Entities.Tax", "Tax")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdTax")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaDetalle_Impuesto");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK_Ropa_CategoriaRopa");

                    b.HasOne("ERP.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("IdWarehouse")
                        .IsRequired()
                        .HasConstraintName("FK_Ropa_Bodega");

                    b.Navigation("Category");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ProductSupplier", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK_RopaProveedor_Ropa");

                    b.HasOne("ERP.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("IdSupplier")
                        .IsRequired()
                        .HasConstraintName("FK_RopaProveedor_Proveedor");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP.Domain.Entities.CreditCard", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PaymentType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Province", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Tax", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
