// <auto-generated />
using System;
using ERP.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCategory")
                        .HasName("PK_CategoriaRopa");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_CategoriaRopa_DescripcionCategoria");

                    b.ToTable("Category", "dbo");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            CategoryName = "Ropa"
                        },
                        new
                        {
                            IdCategory = 2,
                            CategoryName = "Zapatos"
                        },
                        new
                        {
                            IdCategory = 3,
                            CategoryName = "Bolsos"
                        },
                        new
                        {
                            IdCategory = 4,
                            CategoryName = "Accesorios"
                        },
                        new
                        {
                            IdCategory = 5,
                            CategoryName = "Ropa Deportiva"
                        },
                        new
                        {
                            IdCategory = 6,
                            CategoryName = "Ropa Interior"
                        },
                        new
                        {
                            IdCategory = 7,
                            CategoryName = "Joyería"
                        },
                        new
                        {
                            IdCategory = 8,
                            CategoryName = "Cinturones"
                        },
                        new
                        {
                            IdCategory = 9,
                            CategoryName = "Gorras y Sombreros"
                        },
                        new
                        {
                            IdCategory = 10,
                            CategoryName = "Otros"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.CreditCard", b =>
                {
                    b.Property<int>("IdCreditCard")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCreditCard")
                        .HasName("PK_Tarjeta");

                    b.HasIndex(new[] { "CreditCardName" }, "UQ_Tarjeta_DescripcionTarjeta")
                        .IsUnique();

                    b.ToTable("CreditCard");

                    b.HasData(
                        new
                        {
                            IdCreditCard = 1,
                            CreditCardName = "Visa"
                        },
                        new
                        {
                            IdCreditCard = 2,
                            CreditCardName = "Mastercard"
                        },
                        new
                        {
                            IdCreditCard = 3,
                            CreditCardName = "American Express"
                        },
                        new
                        {
                            IdCreditCard = 4,
                            CreditCardName = "Discover"
                        },
                        new
                        {
                            IdCreditCard = 5,
                            CreditCardName = "Diners Club"
                        },
                        new
                        {
                            IdCreditCard = 6,
                            CreditCardName = "JCB"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("IdCustomer")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("IdProvince")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdCustomer")
                        .HasName("PK_Cliente");

                    b.HasIndex("IdProvince");

                    b.HasIndex(new[] { "Email" }, "UQ_Cliente_Email")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdCreditCard")
                        .HasColumnType("int");

                    b.Property<string>("IdCustomer")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<int>("IdInvoiceStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdPaymentType")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("IdInvoice")
                        .HasName("PK_FacturaEncabezado");

                    b.HasIndex("IdCreditCard");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdInvoiceStatus");

                    b.HasIndex("IdPaymentType");

                    b.HasIndex("IdUser");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdTax")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdInvoice", "LineNumber")
                        .HasName("PK_InvoiceItems");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdTax");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Property<int>("IdInvoiceStatus")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceStatusDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdInvoiceStatus")
                        .HasName("PK_EstadoFactura");

                    b.HasIndex(new[] { "InvoiceStatusDescription" }, "UQ_EstadoFactura_DescripcionEstado")
                        .IsUnique();

                    b.ToTable("InvoiceStatuse");

                    b.HasData(
                        new
                        {
                            IdInvoiceStatus = 1,
                            InvoiceStatusDescription = "Pendiente"
                        },
                        new
                        {
                            IdInvoiceStatus = 2,
                            InvoiceStatusDescription = "Pagada"
                        },
                        new
                        {
                            IdInvoiceStatus = 3,
                            InvoiceStatusDescription = "Anulada"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PaymentType", b =>
                {
                    b.Property<int>("IdPaymentType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypeDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdPaymentType")
                        .HasName("PK_TipoPago");

                    b.HasIndex(new[] { "PaymentTypeDescription" }, "UQ_TipoPago_DescripcionTipoPago")
                        .IsUnique();

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            IdPaymentType = 1,
                            PaymentTypeDescription = "Efectivo"
                        },
                        new
                        {
                            IdPaymentType = 2,
                            PaymentTypeDescription = "Tarjeta de Crédito"
                        },
                        new
                        {
                            IdPaymentType = 3,
                            PaymentTypeDescription = "Tarjeta de Débito"
                        },
                        new
                        {
                            IdPaymentType = 4,
                            PaymentTypeDescription = "Transferencia Bancaria"
                        },
                        new
                        {
                            IdPaymentType = 5,
                            PaymentTypeDescription = "SINPE Móvil"
                        },
                        new
                        {
                            IdPaymentType = 6,
                            PaymentTypeDescription = "PayPal"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("IdProduct")
                        .HasName("PK_Ropa");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ProductSupplier", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.HasKey("IdProduct", "IdSupplier")
                        .HasName("PK_RopaProveedor");

                    b.HasIndex("IdSupplier");

                    b.ToTable("ProductSupplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Province", b =>
                {
                    b.Property<int>("IdProvince")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProvince")
                        .HasName("PK_Provincia");

                    b.HasIndex(new[] { "ProvinceName" }, "UQ_Provincia_Descripcion")
                        .IsUnique();

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            IdProvince = 1,
                            ProvinceName = "San José"
                        },
                        new
                        {
                            IdProvince = 2,
                            ProvinceName = "Alajuela"
                        },
                        new
                        {
                            IdProvince = 3,
                            ProvinceName = "Cartago"
                        },
                        new
                        {
                            IdProvince = 4,
                            ProvinceName = "Heredia"
                        },
                        new
                        {
                            IdProvince = 5,
                            ProvinceName = "Guanacaste"
                        },
                        new
                        {
                            IdProvince = 6,
                            ProvinceName = "Puntarenas"
                        },
                        new
                        {
                            IdProvince = 7,
                            ProvinceName = "Limón"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRole")
                        .HasName("PK_Rol");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Rol_DescripcionRol")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            IdRole = 2,
                            RoleName = "Vendedor"
                        },
                        new
                        {
                            IdRole = 3,
                            RoleName = "Cliente"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LegalEntityNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSupplier")
                        .HasName("PK_Proveedor");

                    b.HasIndex(new[] { "LegalEntityNumber" }, "UQ_Proveedor_CedulaJuridica")
                        .IsUnique()
                        .HasFilter("[LegalEntityNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ_Proveedor_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Tax", b =>
                {
                    b.Property<int>("IdTax")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTax")
                        .HasName("PK_Impuesto");

                    b.HasIndex(new[] { "TaxName" }, "UQ_Impuesto_DescripcionImpuesto")
                        .IsUnique();

                    b.ToTable("Taxe");

                    b.HasData(
                        new
                        {
                            IdTax = 1,
                            Percentage = 13m,
                            TaxName = "Impuesto de Ventas"
                        },
                        new
                        {
                            IdTax = 2,
                            Percentage = 15m,
                            TaxName = "Impuesto Selectivo"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdUser")
                        .HasName("PK_Usuario");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuario_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "UQ_Usuario_Login")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdWarehouse")
                        .HasName("PK_Bodega");

                    b.HasIndex(new[] { "WarehouseName" }, "UQ_Bodega_DescripcionBodega")
                        .IsUnique();

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            IdWarehouse = 1,
                            Address = "San José Centro",
                            WarehouseName = "Bodega Central"
                        },
                        new
                        {
                            IdWarehouse = 2,
                            Address = "Escazú, San José",
                            WarehouseName = "Sucursal Escazú"
                        },
                        new
                        {
                            IdWarehouse = 3,
                            Address = "Heredia Centro",
                            WarehouseName = "Sucursal Heredia"
                        },
                        new
                        {
                            IdWarehouse = 4,
                            Address = "Alajuela Centro",
                            WarehouseName = "Sucursal Alajuela"
                        },
                        new
                        {
                            IdWarehouse = 5,
                            Address = "Cartago Centro",
                            WarehouseName = "Sucursal Cartago"
                        },
                        new
                        {
                            IdWarehouse = 6,
                            Address = "San Carlos, Alajuela",
                            WarehouseName = "Centro de Distribución Norte"
                        },
                        new
                        {
                            IdWarehouse = 7,
                            Address = "Pérez Zeledón, San José",
                            WarehouseName = "Centro de Distribución Sur"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Province", "Province")
                        .WithMany("Customers")
                        .HasForeignKey("IdProvince")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Provincia");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("ERP.Domain.Entities.CreditCard", "CreditCard")
                        .WithMany("Invoices")
                        .HasForeignKey("IdCreditCard")
                        .HasConstraintName("FK_FacturaEncabezado_Tarjeta");

                    b.HasOne("ERP.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("IdCustomer")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_Cliente");

                    b.HasOne("ERP.Domain.Entities.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("IdInvoiceStatus")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_EstadoFactura");

                    b.HasOne("ERP.Domain.Entities.PaymentType", "PaymentType")
                        .WithMany("Invoices")
                        .HasForeignKey("IdPaymentType")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_TipoPago");

                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaEncabezado_Usuario");

                    b.Navigation("CreditCard");

                    b.Navigation("Customer");

                    b.Navigation("InvoiceStatus");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdInvoice")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_Invoice");

                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaDetalle_Ropa");

                    b.HasOne("ERP.Domain.Entities.Tax", "Tax")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("IdTax")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaDetalle_Impuesto");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK_Ropa_CategoriaRopa");

                    b.HasOne("ERP.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("IdWarehouse")
                        .IsRequired()
                        .HasConstraintName("FK_Ropa_Bodega");

                    b.Navigation("Category");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ProductSupplier", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK_RopaProveedor_Ropa");

                    b.HasOne("ERP.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("IdSupplier")
                        .IsRequired()
                        .HasConstraintName("FK_RopaProveedor_Proveedor");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP.Domain.Entities.CreditCard", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PaymentType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Province", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Tax", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
